CREATE TABLE EMP01(EMPNO NUMBER(4),ENAME VARCHAR2(200),SAL NUMBER(7,2));

INSERT INTO EMP01(EMPNO,ENAME,SAL) VALUES(0000,'첫번째',2500);
SELECT * FROM EMP01;
COMMIT;

CREATE TABLE DEPT01(DEPTNO NUMBER(2),DNAME VARCHAR2(20),LOC VARCHAR2(20));

ALTER TABLE EMP01 ADD(JOB VARCHAR2(200));

ALTER TABLE DEPT01 ADD(CREDATE DATE);

INSERT INTO EMP01(EMPNO,ENAME,SAL,JOB) VALUES(4,'다섯째',3600,NULL);

ALTER TABLE EMP01 MODIFY(JOB VARCHAR2(30));

UPDATE EMP01 SET JOB=NULL;
COMMIT;

ALTER TABLE EMP01 MODIFY(JOB NUMBER(4));

ALTER TABLE EMP01 MODIFY(EMPNO NUMBER(2));

ALTER TABLE DEPT01 MODIFY(LOC VARCHAR2(200));

ALTER TABLE EMP01 DROP COLUMN JOB;

ALTER TABLE DEPT01 DROP(LOC,CREDATE);

ALTER TABLE DEPT01 ADD(LOC VARCHAR2(20));

RENAME DEPT01 TO DEPT02;

DROP TABLE DEPT02;
DROP TABLE EMP01;

CREATE TABLE EMP01 AS SELECT * FROM EMP;

DELETE FROM EMP01;
ROLLBACK;

TRUNCATE TABLE EMP01;
ROLLBACK;

DROP TABLE EMP01;

CREATE TABLE EMP01 AS SELECT * FROM EMP WHERE 1=0;

DROP TABLE EMP01;

CREATE TABLE EMP01 AS SELECT * FROM EMP;

SELECT EMPNO,ENAME,JOB FROM EMP;
CREATE TABLE EMP02 AS SELECT EMPNO,ENAME,JOB FROM EMP;

CREATE TABLE EMP03 AS SELECT EMPNO,ENAME,JOB FROM EMP WHERE 1=0;

DROP TABLE EMP03;

CREATE TABLE EMP01(EMPNO NUMBER(4),ENAME VARCHAR2(10),JOB VARCHAR2(9),DEPTNO NUMBER(4));

INSERT INTO EMP01 VALUES(NULL,'','SALESMAN',30);
INSERT INTO EMP01 VALUES(NULL,'TOM','SALESMAN',30);
COMMIT;

CREATE TABLE EMP02(EMPNO NUMBER(4) NOT NULL,ENAME VARCHAR2(10)
NOT NULL,JOB VARCHAR2(9),DEPTNO NUMBER(4));

INSERT INTO EMP02 VALUES(NULL,NULL,'SALESMAN',10);
INSERT INTO EMP02 VALUES(1401,'TOM','SALESMAN',10);

CREATE TABLE EMP03(EMPID VARCHAR2(20) UNIQUE NOT NULL,EMPNO NUMBER(4) UNIQUE,
ENAME VARCHAR2(10) NOT NULL,JOB VARCHAR2(9),DEPTNO NUMBER(4));

INSERT INTO EMP03 VALUES('emp03',7499,'ALLEN','SALESMAN',30);
COMMIT;

INSERT INTO EMP03 VALUES('emp02',7499,'JONES','MANAGER',20);

INSERT INTO EMP03 VALUES(NULL,NULL,'JONES','SALESMAN',10);

INSERT INTO EMP03 VALUES('emp02',NULL,'JONES','MANAGER',20);

INSERT INTO EMP03 VALUES('emp05',NULL,'JONES','SALESMAN',10);
COMMIT;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMP03';

CREATE TABLE EMP04(EMPNO NUMBER(4) PRIMARY KEY, ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9), DEPTNO NUMBER(4));

INSERT INTO EMP04 VALUES(7499,'ALLEN','SALESMAN',30);
INSERT INTO EMP04 VALUES(7499,'JONES','MANAGER',20);

CREATE TABLE DEPT01(DEPTNO NUMBER(2) CONSTRAINT DEPT01_DEPTNO_PK PRIMARY KEY,
DNAME VARCHAR2(15), LOC VARCHAR2(15));

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='DEPT01';

CREATE TABLE DEPT02(DEPTNO NUMBER(2), DNAME VARCHAR2(15), LOC VARCHAR2(15),
CONSTRAINT DEPT02_DNO_DEPTNO_DNAME_PK PRIMARY KEY(DEPTNO,DNAME));

INSERT INTO DEPT02 VALUES(15,'영업','서울');

CREATE TABLE DEPT03(DEPTNO NUMBER(2),DNAME VARCHAR2(15),LOC VARCHAR2(15));

ALTER TABLE DEPT03 ADD CONSTRAINT DEPT03_DEPTNO_PK PRIMARY KEY(DEPTNO);

ALTER TABLE DEPT03 MODIFY(DNAME NOT NULL);

ALTER TABLE DEPT03 DROP CONSTRAINT DEPT03_DEPTNO_PK;

INSERT INTO DEPT03 VALUES(15,'영업','서울');
COMMIT;
ALTER TABLE DEPT03 DROP CONSTRAINT  DEPT03_DEPTNO_PK;

CREATE TABLE EMP05(EMPNO NUMBER(4) PRIMARY KEY, ENAME VARCHAR2(10) NOT NULL,
GENDER VARCHAR2(1 CHAR) CHECK(GENDER IN('남','여')));

INSERT INTO EMP05 VALUES(7566,'JONES','M');
INSERT INTO EMP05 VALUES(7566,'JONES','남');
INSERT INTO EMP05 VALUES(7566,'JONES','남남');

CREATE TABLE EMP07(EMPNO NUMBER(4) PRIMARY KEY,ENAME VARCHAR2(10) NOT NULL,
GENDER VARCHAR2(1) CHECK(GENDER IN('M','F')),SAL NUMBER(7,2) CHECK(SAL>=1000 AND SAL<=10000));

INSERT INTO EMP07 VALUES(1234,'TOMS','M',1500);

CREATE TABLE EMP06(EMPNO NUMBER(4) PRIMARY KEY, ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9), DNO NUMBER(4) REFERENCES DEPT01(DEPTNO));

INSERT INTO DEPT01 VALUES(50,'A','뉴욕');
COMMIT;
INSERT INTO EMP06 VALUES(7566,'JONES','MANAGER',50);

INSERT INTO EMP06 VALUES(7990,'S','CEO',90);

DROP TABLE DEPT01 CASCADE CONSTRAINTS;

CREATE TABLE EMP08(EMPNO NUMBER(4) PRIMARY KEY, ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9), DEPTNO NUMBER(4), DNAME VARCHAR2(10),
CONSTRAINT EMP08_DEPTNO_FK FOREIGN KEY(DEPTNO,DNAME) REFERENCES DEPT02(DEPTNO,DNAME));