CREATE TABLE PERSON AS SELECT * FROM CUSTOMERS;

CREATE INDEX TEST.PERSON_INDEX_NM_MAIL ON PERSON(CUST_NAME,CUST_EMAIL);

SELECT * FROM DBA_INDEXES WHERE TABLE_NAME='PERSON';

SELECT CUST_NAME,CUST_EMAIL FROM PERSON WHERE CUST_NAME='Ada Maine'
AND CUST_EMAIL='MaineMaine@company.com';

ALTER INDEX PERSON_INDEX_NM_MAIL RENAME TO PERSON_INDEX;
DROP INDEX PERSON_INDEX;

-----------------------------------------------

CREATE TABLE GOODS_KOR (
   SEQ NUMBER PRIMARY KEY,
   COUNTRY VARCHAR2(10),   
   GOODS VARCHAR(80) NOT NULL
);

CREATE SEQUENCE KOR_SEQ NOCACHE;

INSERT INTO GOODS_KOR (SEQ , COUNTRY , GOODS ) VALUES (1 , '한국', '원유제외 석유류');
INSERT INTO GOODS_KOR VALUES (2 , '한국', '자동차');
INSERT INTO GOODS_KOR VALUES (3 , '한국', '전자집적회로');
INSERT INTO GOODS_KOR VALUES (4 , '한국', '선박');
INSERT INTO GOODS_KOR VALUES (5 , '한국', 'LCD');
INSERT INTO GOODS_KOR VALUES (6 , '한국', '자동차부품');
INSERT INTO GOODS_KOR VALUES (7 , '한국', '휴대전화');
COMMIT;
SELECT * FROM GOODS_KOR ;

-----------------------------------------------

CREATE TABLE GOODS_JAP (
   SEQ NUMBER PRIMARY KEY,
   COUNTRY VARCHAR2(10),   
   GOODS VARCHAR(80) NOT NULL
);

CREATE SEQUENCE JAP_SEQ NOCACHE;

INSERT INTO GOODS_JAP VALUES (1 , '일본', '자동차');
INSERT INTO GOODS_JAP VALUES (2 , '일본', '자동차부품');
INSERT INTO GOODS_JAP VALUES (3 , '일본', '화물차'); 
INSERT INTO GOODS_JAP VALUES (4 , '일본', '건설기계');
INSERT INTO GOODS_JAP VALUES (5 , '일본', '다이오드');
INSERT INTO GOODS_JAP VALUES (6 , '일본', '트랜지스터');
INSERT INTO GOODS_JAP VALUES (7 , '일본', '반도체웨이퍼');
COMMIT;

SELECT * FROM GOODS_JAP ;


SELECT GOODS FROM GOODS_KOR UNION SELECT GOODS FROM GOODS_JAP;

SELECT GOODS FROM GOODS_KOR UNION SELECT GOODS FROM GOODS_JAP;

UPDATE GOODS_JAP SET COUNTRY='한국';
ROLLBACK;

SELECT GOODS FROM GOODS_KOR UNION ALL SELECT GOODS FROM GOODS_JAP ORDER BY GOODS;

UPDATE GOODS_KOR SET GOODS='자동차' WHERE SEQ=3;
UPDATE GOODS_KOR SET GOODS='자동차부품' WHERE SEQ=4;

SELECT GOODS FROM GOODS_KOR INTERSECT SELECT GOODS FROM GOODS_JAP;
ROLLBACK;

SELECT GOODS FROM GOODS_KOR MINUS SELECT GOODS FROM GOODS_JAP;