CREATE TABLE DEPT02 AS SELECT * FROM DEPT WHERE 1=0;

INSERT INTO DEPT01(DEPTNO,DNAME,LOC) VALUES(10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT01(DEPTNO,DNAME) VALUES(40,'ETC');
INSERT INTO DEPT02(DEPTNO,DNAME,LOC) VALUES(10,'ACCOUNTING','NEW YORK');
COMMIT;

INSERT INTO DEPT02 VALUES(60,'ETC','ETC');
COMMIT;

CREATE TABLE EMP05 AS SELECT * FROM EMP;
UPDATE EMP05 SET DEPTNO=30;
ROLLBACK;

UPDATE EMP05 SET SAL=SAL*1.1 WHERE COMM IS NOT NULL;
COMMIT;
ROLLBACK;

UPDATE EMP05 SET HIREDATE=TO_DATE(SYSDATE) WHERE SUBSTR(HIREDATE,1,2) >= 82;
SELECT * FROM EMP05;
ROLLBACK;

UPDATE EMP05 SET COMM=500 WHERE DEPTNO=10;
COMMIT;

UPDATE EMP05 SET JOB='MANAGER',DEPTNO=20 WHERE ENAME='JAMES';
COMMIT;

DELETE FROM EMP05 WHERE DEPTNO=30;
ROLLBACK;

DELETE FROM EMP05 WHERE SUBSTR(HIREDATE,1,2)>=82;
ROLLBACK;

SELECT SAL*12 AS "연봉" FROM EMP05;

SELECT ENAME,JOB,DEPTNO FROM EMP05 WHERE JOB='SALESMAN';

UPDATE EMP05 SET HIREDATE='2001/12/03' WHERE ENAME='SMITH';
COMMIT;
SELECT * FROM EMP05 WHERE HIREDATE='2001/12/03';

SELECT ENAME,SAL FROM EMP05 WHERE SAL BETWEEN 3000 AND 5000;

SELECT EMPNO,MGR,ENAME,DEPTNO FROM EMP05 WHERE SAL>=1500 AND (MGR=7698 OR MGR=7902);

SELECT * FROM EMP05 WHERE COMM=0 OR COMM IS NULL;