SELECT * FROM EMP E,DEPARTMENTS D WHERE E.DEPTNO=D.DEPARTMENT_ID;

SELECT ENAME,DNAME FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

SELECT ENAME,DNAME FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT ENAME,DNAME FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE ENAME='SMITH';

SELECT ENAME,DNAME FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND ENAME='SMITH';

CREATE TABLE TEST1(ID NUMBER(2) CONSTRAINT TEST1_ID_PK PRIMARY KEY,NAME VARCHAR2(10),AGE NUMBER(2));
CREATE TABLE TEST2(ID NUMBER(2) CONSTRAINT TEST2_ID_FK REFERENCES TEST1(ID),JOB VARCHAR2(20));

INSERT INTO test1 VALUES(1, '장희빈', 10);
INSERT INTO test1 VALUES(2, '이효리', 25);
INSERT INTO test1 VALUES(3, '이나영', 40);
INSERT INTO test1 VALUES(4, '이혜리', 35);
INSERT INTO test1 VALUES(5, '주진모', 15);

INSERT INTO test2 VALUES(1, '백수');
INSERT INTO test2 VALUES(3, '백조');
INSERT INTO test2 VALUES(5, '날라리');
INSERT INTO test2 VALUES(3, '강사');
commit;

SELECT * FROM TEST1 T1 JOIN TEST2 T2 ON T1.ID=T2.ID;

SELECT T1.ID,NAME,AGE,JOB FROM TEST1 T1 JOIN TEST2 T2 ON T1.ID=T2.ID;

SELECT EMP.ENAME,DEPT.DNAME FROM EMP INNER JOIN DEPT USING (DEPTNO) WHERE ENAME='SMITH';

SELECT * FROM TEST1 T1 LEFT OUTER JOIN TEST2 T2 ON T1.ID=T2.ID;
SELECT * FROM TEST1 T1,TEST2 T2 WHERE T1.ID=T2.ID(+);

ALTER TABLE TEST2 DROP CONSTRAINT TEST2_ID_FK;

INSERT INTO TEST2 VALUES (9,'개발');
COMMIT;

SELECT * FROM TEST1 T1 RIGHT OUTER JOIN TEST2 T2 USING(ID);
SELECT * FROM TEST1 T1,TEST2 T2 WHERE T1.ID(+)=T2.ID;

SELECT EMP.*,DEPT.DNAME FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT EMP.*,D.DNAME FROM EMP,(SELECT * FROM DEPT WHERE DEPTNO<=20) D WHERE EMP.DEPTNO=D.DEPTNO;

SELECT * FROM TEST1 T1 FULL OUTER JOIN TEST2 T2 USING(ID);

SELECT EMP.ENAME,DEPT.DNAME FROM EMP JOIN DEPT USING(DEPTNO) WHERE DEPTNO=10;

SELECT ENAME,D.DNAME FROM EMP,(SELECT * FROM DEPT WHERE DEPTNO=10) D WHERE EMP.DEPTNO=D.DEPTNO;

SELECT * FROM DEPT B WHERE B.DEPTNO IN(SELECT DISTINCT DEPTNO FROM EMP WHERE SAL>=3000);

SELECT * FROM DEPT B WHERE EXISTS(SELECT * FROM EMP E WHERE E.DEPTNO=B.DEPTNO);

SELECT * FROM EMP E WHERE EXISTS(SELECT * FROM DEPT B WHERE E.DEPTNO=B.DEPTNO);

SELECT * FROM DEPT B WHERE NOT EXISTS(SELECT * FROM EMP E WHERE E.DEPTNO=B.DEPTNO);
SELECT * FROM EMP E WHERE NOT EXISTS(SELECT * FROM DEPT B WHERE B.DEPTNO=E.DEPTNO);
SELECT * FROM DEPT B WHERE B.DEPTNO NOT IN(SELECT DISTINCT DEPTNO FROM EMP WHERE SAL>=3000);

SELECT E.EMPNO,E.ENAME,D.DEPTNO,D.DNAME,D.LOC FROM EMP E,DEPT D;
SELECT E.EMPNO,E.ENAME,D.DEPTNO,D.DNAME,D.LOC FROM EMP E CROSS JOIN DEPT D;

SELECT E.JOB_ID,E.EMPLOYEE_ID,J.START_DATE FROM JOB_HISTORY J,EMPLOYEES E
WHERE E.JOB_ID=J.JOB_ID ORDER BY E.JOB_ID;


--INT자료형 (= NUMBER(38)과 동일) : 음수,0,양수만 표현
CREATE TABLE board (
  no INT PRIMARY KEY,
  subject VARCHAR2(30),
  content VARCHAR2(50),
  w_date DATE
);

CREATE SEQUENCE SEQ_NO NOCACHE;
-- board의 no 컬럼에 사용할 시퀀스 생성

INSERT INTO board VALUES(seq_no.NEXTVAL, 'java1', 'java', sysdate);
INSERT INTO board VALUES(seq_no.NEXTVAL, 'java2', '자바', sysdate);
INSERT INTO board VALUES(seq_no.NEXTVAL, 'java3', 수업, sysdate);
INSERT INTO board VALUES(seq_no.NEXTVAL, 'java3', '수업', sysdate);
SELECT SEQ_NO.CURRVAL FROM DUAL;
SELECT * FROM board;

INSERT INTO board VALUES(seq_no.NEXTVAL, 'java3', '수업', sysdate);
SELECT * FROM BOARD;

DELETE FROM board WHERE NO=4;
SELECT *FROM board;

INSERT INTO board VALUES(seq_no.NEXTVAL, 'java2', '영어', sysdate);
SELECT *FROM board;

TRUNCATE TABLE BOARD;
DROP SEQUENCE SEQ_NO;
CREATE SEQUENCE SEQ_NO NOCACHE;

SELECT * FROM USER_SEQUENCES;

INSERT INTO board VALUES(seq_no.NEXTVAL, 'java1', 'java', sysdate);
INSERT INTO board VALUES(seq_no.NEXTVAL, 'java2', '자바', sysdate);
INSERT INTO board VALUES(seq_no.NEXTVAL, 'java3', '수업', sysdate);
INSERT INTO board VALUES(seq_no.NEXTVAL, '', '영어', sysdate);
INSERT INTO board VALUES(seq_no.NEXTVAL, 'java2', '국어', sysdate);
--INSERT INTO board VALUES(seq_no.NEXTVAL, 'java2', '고어', sysdate);
--INSERT INTO board VALUES(seq_no.NEXTVAL, 'java2', '수학', sysdate);
--INSERT INTO board VALUES(seq_no.NEXTVAL, 'java2', '한문', sysdate);
SELECT * FROM board;
SELECT SEQ_NO.CURRVAL FROM DUAL;
ROLLBACK;

--시퀀스를 MAX부터 -1씩 감소
CREATE SEQUENCE SEQ_NO
START WITH 5 --이 부분은 생략가능
INCREMENT BY -1
MAXVALUE 5 --이 부분은 생략불가, START값이 MAX보다 크면 안됨
NOCACHE; --이 부분은 생략가능, 디폴트가 NOCACHE

ALTER TABLE BOARD MODIFY(SUBJECT NOT NULL);
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='BOARD';

COMMIT;

CREATE TABLE EMP07 AS SELECT SEQ_NO.NEXTVAL,EMPNO,ENAME,DEPTNO,SAL,JOB FROM EMP;

ALTER TABLE EMP07 DROP COLUMN NEXTVAL;
TRUNCATE TABLE EMP07;

INSERT INTO EMP07 VALUES(SEQ_NO.NEXTVAL,'MARIA',90,6000,'BABO');

UPDATE EMP07 SET EMPNO=SEQ_NO.NEXTVAL,DEPTNO=SEQ_NO.NEXTVAL WHERE EMPNO=18;

DROP TABLE PRODUCTS;