SET SERVEROUTPUT ON

--함수 생성
--예제 (매개변수가 있는 함수)
CREATE OR REPLACE FUNCTION TEST_FUNC(P_N1 EMP.ENAME%TYPE)
RETURN DEPT.DNAME%TYPE
IS V_DNAME DEPT.DNAME%TYPE; V_DEPTNO EMP.DEPTNO%TYPE;
BEGIN SELECT DEPTNO INTO V_DEPTNO FROM EMP WHERE ENAME=P_N1;
SELECT DNAME INTO V_DNAME FROM DEPT WHERE DEPTNO=V_DEPTNO;
RETURN V_DNAME; END;
/

CREATE OR REPLACE FUNCTION TOPNAME_FNC RETURN EMP.ENAME%TYPE
IS V_ENAME EMP.ENAME%TYPE;
BEGIN SELECT ENAME INTO V_ENAME FROM EMP WHERE SAL=(SELECT MAX(SAL) FROM EMP);
RETURN V_ENAME; END;
/

SELECT TOPNAME_FNC FROM DUAL;

DECLARE V_ENAME EMP.ENAME%TYPE;
BEGIN SELECT TOPNAME_FNC INTO V_ENAME FROM DUAL;
DBMS_OUTPUT.PUT_LINE('V_ENAME : '||V_ENAME);
END;
/

CREATE OR REPLACE FUNCTION MY_MUL(N1 NUMBER,N2 NUMBER)
RETURN NUMBER IS V_RES NUMBER;
BEGIN V_RES:=N1*N2;
RETURN V_RES;
END;
/

SELECT MY_MUL(2,2) FROM DUAL;

DECLARE V_RES NUMBER;
BEGIN SELECT MY_MUL(5,3) INTO V_RES FROM DUAL;
DBMS_OUTPUT.PUT_LINE(V_RES);
END;
/

CREATE PROCEDURE TEST IS
BEGIN DBMS_OUTPUT.PUT_LINE('Hello Function~');
END;
/

EXEC TEST;

CREATE OR REPLACE PROCEDURE MY_ADD(N1 NUMBER,N2 NUMBER) IS V_SUM NUMBER;
BEGIN V_SUM:=N1+N2; DBMS_OUTPUT.PUT_LINE(V_SUM);
END;
/

CREATE OR REPLACE PROCEDURE MY_ADD01(N1 NUMBER,N2 NUMBER) IS
BEGIN DBMS_OUTPUT.PUT_LINE(N1+N2);
END;
/

EXEC MY_ADD01();

CREATE OR REPLACE PROCEDURE MY_ADD01(N1 NUMBER:=5,N2 NUMBER:=7) --디폴트는 IN
IS BEGIN DBMS_OUTPUT.PUT_LINE(N1+N2);
END;
/

CREATE OR REPLACE PROCEDURE MY_NEW_JOB_PROC
(   P_JOB_ID    IN  JOBS.JOB_ID%TYPE,
    P_JOB_TITLE IN  JOBS.JOB_TITLE%TYPE,
    P_MIN_SAL   IN  JOBS.MIN_SALARY%TYPE := 10,
    P_MAX_SAL   IN  JOBS.MAX_SALARY%TYPE := 100,
    P_UPDATE_DATE OUT JOBS.UPDATE_DATE%TYPE     )
IS
    VN_CNT  NUMBER := 0;
    VN_CUR_DATE JOBS.UPDATE_DATE%TYPE := SYSDATE;
BEGIN
    SELECT  COUNT(*)
    INTO    VN_CNT
    FROM    JOBS
    WHERE   JOB_ID = P_JOB_ID;
    
    IF  VN_CNT > 0  THEN
        UPDATE  JOBS
        SET     JOB_TITLE   = P_JOB_TITLE,
                MIN_SALARY  = P_MIN_SAL,
                MAX_SALARY  = P_MAX_SAL,
                UPDATE_DATE = VN_CUR_DATE
        WHERE   JOB_ID = P_JOB_ID;
    ELSE
        INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY, CREATE_DATE, UPDATE_DATE)
        VALUES (P_JOB_ID, P_JOB_TITLE, P_MIN_SAL, P_MAX_SAL, SYSDATE, SYSDATE);
    END IF;
    
    P_UPDATE_DATE := VN_CUR_DATE;
    
    COMMIT;
END;
/ 

DECLARE VD_CUR_DATE JOBS.UPDATE_DATE%TYPE;
BEGIN MY_NEW_JOB_PROC('ST_CLERK','SAMPLE JOB1',2000,6000,VD_CUR_DATE);
DBMS_OUTPUT.PUT_LINE(VD_CUR_DATE); END;
/