SELECT SAL, SAL/12 AS 월급 FROM EMP;

SELECT ENAME||'의 직책은 '||JOB||'입니다' AS WORDS FROM EMP WHERE ENAME='SMITH';

SELECT ENAME, ' IS A ' AS " i   s ", JOB FROM EMP;

SELECT ENAME||' IS A '||JOB FROM EMP;

SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE>='1982/01/01' OR JOB='MANAGER';

SELECT EMPNO NO, ENAME NM, DEPTNO DNO FROM EMP WHERE DEPTNO=30 ORDER BY NM;

SELECT EMPNO,ENAME,COMM FROM EMP WHERE COMM=300 OR COMM=500 OR COMM=1400;
SELECT EMPNO,ENAME,COMM FROM EMP WHERE COMM>0;
SELECT EMPNO,ENAME,COMM FROM EMP WHERE COMM NOT IN(0);

SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL>=2500 AND SAL<=4000;
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL BETWEEN 2500 AND 4000;
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE BETWEEN '1982/01/01' AND '1987/12/31';

SELECT COUNT(*) FROM EMP;
SELECT COUNT(COMM) FROM EMP;

SELECT DEPTNO, SUM(SAL)/COUNT(*) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO;

SELECT SUM(COMM)/COUNT(*) FROM EMP;
SELECT SUM(COMM)/COUNT(COMM) FROM EMP;
SELECT AVG(COMM) FROM EMP;

SELECT COMM, COUNT(COMM) FROM EMP GROUP BY COMM;
SELECT COMM, COUNT(*) FROM EMP GROUP BY COMM;

SELECT DEPTNO, AVG(SAL) FROM EMP WHERE SAL>=2000 GROUP BY DEPTNO ORDER BY DEPTNO;

SELECT MGR,JOB,SUM(SAL) FROM EMP WHERE NOT MGR IS NULL GROUP BY MGR,JOB ORDER BY MGR;

SELECT DEPTNO AS 부서번호,COUNT(DEPTNO)||'명' AS 연봉2500이상 FROM EMP WHERE SAL>=2500 GROUP BY DEPTNO ORDER BY DEPTNO;

SELECT DEPTNO,COUNT(DEPTNO)||'명' AS 인원수,AVG(SAL),SUM(SAL) FROM EMP GROUP BY DEPTNO HAVING 5<=COUNT(DEPTNO) ORDER BY DEPTNO;

SELECT DEPTNO,AVG(SAL) AS "2000 이상" FROM EMP WHERE SAL>=1000 GROUP BY DEPTNO HAVING AVG(SAL)>=2000 ORDER BY DEPTNO;

SELECT COUNT(*),DEPTNO,JOB,SUM(SAL) FROM EMP WHERE DEPTNO=30 GROUP BY DEPTNO,JOB;
SELECT COUNT(*),DEPTNO,JOB,SUM(SAL) FROM EMP GROUP BY DEPTNO,JOB HAVING DEPTNO=30;

SELECT * FROM EMP;

SELECT * FROM DUAL;
SELECT FLOOR(34.5678) FROM DUAL;

SELECT ROUND(345.678,2) FROM DUAL;
SELECT ROUND(345.678,1) FROM DUAL;
SELECT ROUND(345.678) FROM DUAL;
SELECT ROUND(345.678,-1) FROM DUAL;
SELECT ROUND(345.678,-2) FROM DUAL;
SELECT MOD(5,3) FROM DUAL;

--사원테이블에서 사번이 짝수인 사람들의 사번,이름,직책을 검색하세요

SELECT EMPNO,ENAME,JOB FROM EMP WHERE MOD(EMPNO,2)=0 ORDER BY EMPNO;

SELECT SYSDATE-1 어제,SYSDATE 오늘,SYSDATE+1 내일 FROM DUAL;

SELECT ENAME,SYSDATE,HIREDATE,ROUND(ROUND(SYSDATE-HIREDATE)/360) FROM EMP WHERE DEPTNO=10;

SELECT HIREDATE,ROUND(HIREDATE,'DAY') FROM EMP;

SELECT 'DataBase',LOWER('DataBase'),UPPER('DataBase') FROM DUAL;

SELECT ENAME, LOWER(ENAME) FROM EMP;

SELECT INITCAP('DATA BA''SE PROGRAM') FROM DUAL;

SELECT CONCAT(CONCAT('Data','Base'),'BASE') FROM DUAL;

SELECT LENGTH('한글'),LENGTHB('한글'),LENGTH('HI'),LENGTHB('HI') FROM DUAL;

SELECT * FROM EMP WHERE LENGTH(ENAME)<=4;

SELECT SUBSTR('DATABASE',-5,4) FROM DUAL;

SELECT ENAME,SUBSTR(HIREDATE,1,2) FROM EMP WHERE DEPTNO=20;

SELECT COUNT(*),SUBSTR(HIREDATE,1,2) FROM EMP GROUP BY SUBSTR(HIREDATE,1,2);

SELECT ENAME,HIREDATE FROM EMP WHERE SUBSTR(HIREDATE,1,2)=82;

SELECT ENAME FROM EMP WHERE SUBSTR(ENAME,-1,1)='S';
SELECT ENAME FROM EMP WHERE ENAME LIKE '%S';

SELECT SUBSTR('데이터베이스',3,4),SUBSTRB('데이터베이스',1,5),SUBSTRB('데이터베이스',1,6) FROM DUAL;

SELECT LPAD('DataBase',20,'$') FROM DUAL;
SELECT RPAD('DataBase',20,'$') FROM DUAL;

SELECT LTRIM('aaaaDataBase Programingaaaa','a'),
RTRIM('aaaaDataBase Programingaaaa','a'),
TRIM('a' FROM 'aaaaDataBase Programingaaaa') FROM DUAL;

SELECT ENAME,TRIM('S' FROM ENAME),TRIM('H' FROM ENAME) FROM EMP WHERE ENAME='SMITH';

