SELECT SYSDATE, TO_CHAR(SYSDATE,'YYYY-MM-DD HH12"시"MI:SS AM DAY') FROM DUAL;

SELECT HIREDATE, TO_CHAR(HIREDATE,'YYYY"년" MM"월" DD"일" DAY') FROM EMP;

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS AM DAY ','NLS_DATE_LANGUAGE=AMERICAN') AS AMERICAN,
TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS AM DAY','nls_date_language=korean') AS KOREAN FROM DUAL;

SELECT TO_CHAR(123456,'000,000,000') FROM DUAL;
SELECT TO_CHAR(123456,'999,999,999') FROM DUAL;

SELECT ENAME,SAL,TO_CHAR(SAL,'L999,999') FROM EMP WHERE DEPTNO=10;
SELECT ENAME,SAL,TO_CHAR(SAL,'$999,999') FROM EMP WHERE DEPTNO=10;

SELECT TRUNC((SYSDATE-TO_DATE('2011-01-01','YYYY/MM/DD'))/365) FROM DUAL;

SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE=TO_DATE(19810220,'YYYYMMDD');

SELECT SYSDATE,SYSTIMESTAMP FROM DUAL;
SELECT TO_DATE(SYSDATE,'YYYY-MM-DD HH24:MI:SS'),SYSTIMESTAMP FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'),SYSTIMESTAMP FROM DUAL;
SELECT TO_DATE(SYSDATE,'YYYY-MM-DD HH24:MI:SS'),TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DD HH24:MI:SS.FF3')
FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'토요일') FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'금') FROM DUAL;
SELECT NEXT_DAY(SYSDATE,1) FROM DUAL;
SELECT NEXT_DAY(SYSDATE-8,'토요일') FROM DUAL;

SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2011-01-01','YYYY/MM/DD')) FROM DUAL;

SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE('2011-01-01','YYYY/MM/DD'))/12) FROM DUAL;

SELECT TO_NUMBER('10,000','999,999')+TO_NUMBER('20,000','999,999') AS SUM FROM DUAL;

SELECT TO_NUMBER('10,000','999,999') FROM DUAL;

SELECT ENAME,SAL,COMM,JOB FROM EMP;
SELECT ENAME,SAL,NVL(COMM,0),JOB FROM EMP;
SELECT AVG(NVL(COMM,0)) AS AVG FROM EMP;
SELECT AVG(COMM) AS AVG FROM EMP;

SELECT ENAME,SAL,COMM,SAL*12+COMM FROM EMP;
SELECT ENAME,SAL,COMM,SAL*12+NVL(COMM,0) FROM EMP;
SELECT ENAME, NVL(TO_CHAR(MGR,'9999'),'CEO') FROM EMP;

SELECT ENAME,COMM,MGR,SAL,NVL2(COMM,MGR,SAL) FROM EMP;

SELECT COMM,EMPNO FROM EMP WHERE COMM=0;
SELECT COMM,EMPNO FROM EMP WHERE NVL(COMM,0)=0;

SELECT INSTR('DataBase','B') FROM DUAL;
SELECT INSTR('DataBase','b') FROM DUAL;

SELECT INSTR('DataBase','a',3,2) FROM DUAL;

SELECT POWER(5,2), ROUND(SQRT(2),4) FROM DUAL;

SELECT ENAME,DEPTNO,DECODE(DEPTNO,10,'ACCOUNTING',20,'RESEARCH','ETC') AS DNAME FROM EMP;

SELECT ENAME,JOB,SAL,DECODE(JOB,'ANALYST',SAL+SAL*0.05,'SALESMAN',SAL+SAL*0.1,
'MANAGER',SAL+SAL*0.15,'CLERK',SAL+SAL*0.2) AS 급여인상 FROM EMP;

SELECT ENAME, DEPTNO, CASE WHEN DEPTNO=10 THEN 'ACCOUNTING' WHEN DEPTNO=20 THEN 'RESEARCH'
ELSE 'OPERATIONS' END AS DNAME FROM EMP;

SELECT ENAME,JOB,SAL,CASE JOB WHEN 'ANALYST' THEN (SAL+SAL*0.05)
WHEN 'SALESMAN' THEN(SAL+SAL*0.1) WHEN 'MANAGER' THEN (SAL+SAL*0.15) 
WHEN 'CLERK' THEN (SAL+SAL*0.2) END 급여인상 FROM EMP;