SELECT DNAME FROM DEPT WHERE PEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='JONES');

SELECT EMPNO,ENAME,JOB,HIREDATE,MGR FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SMITH');

SELECT ENAME,SAL FROM EMP WHERE SAL>(SELECT AVG(SAL) FROM EMP) ORDER BY SAL;

SELECT * FROM EMP WHERE SAL>(SELECT AVG(SAL) FROM EMP) ORDER BY SAL DESC;

SELECT EMPNO,ENAME FROM EMP WHERE SAL=(SELECT MAX(SAL) FROM EMP WHERE DEPTNO=10);

SELECT DEPTNO,DNAME FROM DEPT WHERE DEPTNO!=(SELECT DEPTNO FROM EMP WHERE ENAME='KING');

SELECT DEPTNO,DNAME FROM DEPT WHERE DEPTNO IN (SELECT DISTINCT DEPTNO FROM EMP WHERE DEPTNO!=
(SELECT DEPTNO FROM EMP WHERE ENAME='KING'));

SELECT ENAME,HIREDATE FROM EMP WHERE DEPTNO NOT IN (SELECT DEPTNO FROM EMP WHERE ENAME='BLAKE');

SELECT ENAME,SAL,DEPTNO FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL>=3000);

SELECT ENAME,SAL,DEPTNO FROM EMP WHERE SAL IN (SELECT MIN(SAL) FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP WHERE SAL<ALL(1000,2000,3000) ORDER BY SAL;

SELECT * FROM EMP WHERE SAL>ALL(1000,2000,3000) ORDER BY SAL;

SELECT ENAME, SAL FROM EMP WHERE SAL>ALL(SELECT SAL FROM EMP WHERE DEPTNO=30);

SELECT ENAME,SAL FROM EMP WHERE SAL<ALL(SELECT SAL FROM EMP WHERE DEPTNO=30);

SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO;
SELECT * FROM EMP WHERE SAL>ALL(SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP WHERE SAL<ANY(1000,2000,3000) ORDER BY SAL;

SELECT * FROM EMP WHERE SAL>ANY(1000,2000,3000) ORDER BY SAL;

SELECT ENAME,SAL FROM EMP WHERE SAL>ANY(SELECT SAL FROM EMP WHERE DEPTNO=30);

SELECT ENAME,SAL FROM EMP WHERE SAL<ANY(SELECT SAL FROM EMP WHERE DEPTNO=30);

SELECT EMPNO,ENAME,JOB,SAL FROM EMP WHERE SAL<ANY(SELECT SAL FROM EMP WHERE JOB='CLERK')
AND JOB!='CLERK';

CREATE TABLE EMP05 AS SELECT * FROM EMP WHERE 1=0;

INSERT ALL INTO EMP04 VALUES(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) SELECT * FROM EMP;

ROLLBACK;

INSERT INTO EMP04 SELECT * FROM EMP;

INSERT ALL INTO EMP04(EMPNO,ENAME,DEPTNO) VALUES(EMPNO,ENAME,DEPTNO)
SELECT EMPNO,ENAME,DEPTNO FROM EMP;

INSERT ALL INTO EMP04 INTO EMP05 VALUES(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) SELECT * FROM EMP;

ALTER TABLE EMP04 DROP(MGR,HIREDATE,SAL,COMM,DEPTNO);
ALTER TABLE EMP05 DROP(HIREDATE,SAL,COMM,DEPTNO);

INSERT ALL INTO EMP04(EMPNO,ENAME,JOB) VALUES(EMPNO,ENAME,JOB) INTO EMP05(EMPNO,ENAME,MGR,JOB)
VALUES(EMPNO,ENAME,MGR,JOB) SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO FROM EMP;

INSERT ALL INTO EMP04 VALUES(EMPNO,ENAME,JOB) INTO EMP05
VALUES(EMPNO,ENAME,JOB,MGR) SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO FROM EMP;

ROLLBACK;

ALTER TABLE EMP05 ADD(COMM NUMBER(4));

INSERT ALL INTO EMP01(EMPNO,ENAME,JOB) INTO EMP02(EMPNO,ENAME,JOB,MGR)
VALUES(EMPNO,ENAME,JOB,MGR) SELECT EMPNO,ENAME,JOB,MGR FROM EMP;

ALTER TABLE EMP02 DROP(HIREDATE,SAL,COMM,DEPTNO);

DROP TABLE EMP02 PURGE;

CREATE TABLE DEPT01 AS SELECT * FROM DEPT;

UPDATE DEPT01 SET LOC=(SELECT LOC FROM DEPT01 WHERE DEPTNO=40) WHERE DEPTNO=10;

UPDATE DEPT01 SET (DNAME,LOC)=(SELECT DNAME,LOC FROM DEPT01 WHERE DEPTNO=30) WHERE DEPTNO=40;

ROLLBACK;

CREATE TABLE EMP01 AS SELECT * FROM EMP;

UPDATE EMP01 SET (EMPNO,ENAME)=(SELECT 1111,'첫째' FROM DUAL);

ALTER TABLE EMP01 ADD(DNAME	VARCHAR2(14));

UPDATE EMP01 SET DNAME=(SELECT DNAME FROM DEPT WHERE DEPT.DEPTNO=EMP01.DEPTNO);

ALTER TABLE EMP01 DROP (DNAME);

DELETE FROM EMP01 WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');
 
SELECT ENAME,DNAME FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT ENAME,DNAME,EMP.DEPTNO FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT E.ENAME,D.DNAME,E.DEPTNO AS EDNO,D.DEPTNO AS DDNO FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO
ORDER BY DDNO;

SELECT D.DNAME AS DDNM,E.DEPTNO AS EDNO,D.DEPTNO AS DDNO FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO GROUP BY D.DNAME,E.DEPTNO,D.DEPTNO HAVING(D.DEPTNO=10) ORDER BY DDNO;

SELECT E.ENAME,D.DNAME FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO AND E.ENAME='SMITH';

SELECT E.ENAME,D.DNAME,D.LOC FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO AND COMM IS NOT NULL;

SELECT E.ENAME,D.DNAME FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO AND E.ENAME LIKE '%A%';

SELECT E.ENAME "사원이름",E.EMPNO "사원번호",D.ENAME "관리자이름",D.EMPNO "관리자번호"
FROM EMP E,EMP D WHERE E.MGR=D.EMPNO;

SELECT WORK.ENAME||'의 매니저는 '||MANAGER.ENAME FROM EMP WORK,EMP MANAGER
WHERE WORK.MGR=MANAGER.EMPNO;

SELECT ENAME,MGR,(SELECT DISTINCT ENAME FROM EMP E1 WHERE E.MGR=E1.EMPNO) MNAME FROM EMP E;